"""remove available_seats

Revision ID: 3e6feeee8aab
Revises: 72efe0259ff1
Create Date: 2026-05-17 01:45:56.795993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6feeee8aab'
down_revision: Union[str, None] = '72efe0259ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'available_seats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('available_seats', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
