"""initial

Revision ID: 72efe0259ff1
Revises: 
Create Date: 2026-05-16 19:30:08.254887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72efe0259ff1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fraud_log_fraud_log_id', table_name='fraud_log')
    op.drop_table('fraud_log')
    op.add_column('movies', sa.Column('age_rating', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'age_rating')
    op.create_table('fraud_log',
    sa.Column('fraud_log_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_blocked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('fraud_log_id', name='fraud_log_pkey'),
    sa.UniqueConstraint('booking_id', name='fraud_log_booking_id_key')
    )
    op.create_index('ix_fraud_log_fraud_log_id', 'fraud_log', ['fraud_log_id'], unique=False)
    # ### end Alembic commands ###
