"""add training tables

Revision ID: a8210cdc3621
Revises: 3e6feeee8aab
Create Date: 2026-05-17 02:13:23.436778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8210cdc3621'
down_revision: Union[str, None] = '3e6feeee8aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('is_weekend', sa.Integer(), nullable=True),
    sa.Column('session_hour', sa.Integer(), nullable=True),
    sa.Column('ticket_price', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('occu_perc', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_data_id'), 'training_data', ['id'], unique=False)
    op.create_table('training_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('model_path', sa.String(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('mse', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('r2', sa.Float(), nullable=True),
    sa.Column('samples_count', sa.Integer(), nullable=True),
    sa.Column('features_used', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_history_id'), 'training_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_history_id'), table_name='training_history')
    op.drop_table('training_history')
    op.drop_index(op.f('ix_training_data_id'), table_name='training_data')
    op.drop_table('training_data')
    # ### end Alembic commands ###
